### ISSUE TITLE
Will not download GDAL data

### ISSUE THREAD

**Issue by paulopulgarin** [mstrimas/ebird-best-practices#10]
Dear all,

On a MacOS, trying to download the MODIS data...I get this:

ERROR 4: `/private/var/folders/cq/_jgt3h0s20v3zb_d7qk9pj080000gn/T/Rtmp0sA0Uj/MODIS_ARC/MODIS/MCD12Q1.006/2009.01.01/MCD12Q1.A2009001.h10v08.006.2018054192001.hdf' not recognized as a supported file format.

I have followed all the instructions...using homebrew and chacking that GDAL is installed.

Any suggestions?

**Comment by mstrimas** [comment]
Hi Paulo, these MODIS/GDAL issues can be quite challenging to work through because they're very system specific. We've given instructions to cover most scenarios and don't have the resources to troubleshoot specific problems, particularly because these issues are hard to diagnose remotely. A couple general points of advice:

1. It's not enough that GDAL is installed, you need to ensure it has HDF support by running `gdal-config --formats` and looking for `hdf4` in the list
2. It's possible you have multiple versions of GDAL installed, for example if you installed QGIS this would happen, you may need to specific the specific version that you installed with Homebrew using `MODIS::MODISoptions(gdalPath = "path")`, where `"path"` is the directory with the GDAL binaries. 
3. Find someone locally that has experience with this stuff. These problems are much easier to troubleshoot in person.

Good luck!
