### ISSUE TITLE
Recommendation: list length as effort variable

### ISSUE THREAD

**Issue by aeiche01** [mstrimas/ebird-best-practices#13]
Possible suggestion: there have been a few papers published that suggest using list length as a useful effort variable for ebird data (meaning, list length = the number of species reported in a list. The more species, the more likely the reporter is a skilled birder). Adding that in as a possible effort variable for encounter rates might help make the maps more accurate.

The only problem I've been running into is the sheer size of the ebird dataset. I feel like the code to add a list_length column is pretty simple (group by checklist_id, count the number of different scientific_names in each group or something similar), but actually doing that would require one to filter auk for all the species in a study area. At larger scales (such as state, country, etc) the resulting dataset would still be too big for R to work with...unless there were another dataset with information on the total number of species observed in a checklist that could just be joined to the zero-filled datasheet?

**Comment by mstrimas** [comment]
The Checklist Calibration Index (CCI) is meant to account for exactly this. We use it for our modeling efforts internally, but are still figuring out how best to share it publicly since there are some privacy related issues that we need to work through. Hopefully in the near future that will be made available as an additional covariate.

**Comment by aeiche01** [comment]
Ah I see! That makes a lot of sense
