### ISSUE TITLE
trouble replicating WOTH encounter rate map from example

### ISSUE THREAD

**Issue by TeresaPegan** [mstrimas/ebird-best-practices#9]
I've run all the code in Chapter 4 (modeling encounter rate) on my lab computer, using the data provided as a download in the bookdown, and the resulting encounter rate probability map I get is quite different from the one shown in the bookdown. Whereas the bookdown's map shows large areas where Wood Thrush encounter probability should be high in most of the region (http://strimas.com/ebird-best-practices/encounter.html), the map I end up has lower encounter probabilities, showing most of the area with an encounter probability close to 0.

![image](https://user-images.githubusercontent.com/35701568/60982848-e6dec080-a306-11e9-9a98-37f276f4eee1.png)

I know that the bookdown is able to use the CCI data that haven't been made public yet, but is it possible that would cause such a serious difference between the two maps? There are a few other places where my results are slightly different from those in the bookdown (most of which are probably attributable to the fact that I didn't use the CCI), but nothing as extreme as the difference in the maps. 

To ensure this wasn't related to a typo or mistake copying the code over I tried it twice, independently downloading the data and copying the code over each time, and got the same result. I'm using R version 3.6.0, RStudio 1.2.1335, and I updated all of my packages before running. Any ideas what might have caused the discrepancy? Thanks!

**Comment by mstrimas** [comment]
There's a good chance this is caused by not having access to the CCI data. For example, if I run the code exactly as it appears in the bookdown, but don't use CCI, I get this:

![no-cci](https://user-images.githubusercontent.com/7296482/60997616-3d5af780-a325-11e9-912a-65c04ec81ef4.png)

Which isn't quite as extreme as the map you have but it's close. The remaining differences could be related to other changes you've made or just random chance from the sub-sampling process.

**Comment by TeresaPegan** [comment]
Thanks!
